name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Create build directory
      run: mkdir build 
    - name: Run CMake
      run: cd build && cmake -G Ninja ..
    - name: Run Ninja
      run: ninja
